### ISSUE TITLE
Bootscript

### ISSUE THREAD

**Issue by martinbaranek** [ZoltanOnody/ledky#1]
Added crontab task:
/home/martin/bootscript.sh runs after boot of RPi. 
Currently enables venv, and runs backend FLASK app.
(nechcel som to dávať ako pullrequest, keďže je to vec raspberryčka, a nie lediek, ale bolo by fajn mať niekde spísané, čo sa kde a ako robí)

**Comment by ZoltanOnody** [comment]
Kľudne to daj ako PR. Tento repozitar ma slúžiť pre nás (ako záloha) , aj veci co sú hardware specific tu teda môžu byť.

**Comment by martinbaranek** [comment]
Ok, len musím zmeniť veci v crontabe a dať to do zložky ledky, aby to bolo
kompatibilné :) máš potom PR tam na tlačítka. Musím pozrieť potom tutorial
ako to mergnuť do RPi.

Dňa so 24. 3. 2018, 23:36 Zoltan Onody <notifications@github.com>
napísal(a):

**Comment by ZoltanOnody** [comment]
deployovanie by na RPi by sme mohli zautomatizovat. Momentalne to vsak funguje tak, ze lokalne napises `npm build` a zlozku build vykopirujes na RPi do `/var/www` (deploymnet FE).

**Comment by martinbaranek** [comment]
ah. myslel som, že stačilo dať git pull origin master a už automaticky....
môžem to zoskriptovať. otestujem teraz.

**Comment by ZoltanOnody** [comment]
well, kedze na RPi nechceme instalovat npm, react,... (to nepatri na produkcny environment), tak mi napada iba to, ze budeme commitovat aj `build` zlozku vo `frontend`. Osobne s tym problem nemam.
